[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.coverage.html]
directory = "test_results/cov_html"

[tool.coverage.xml]
output = "test_results/cov_xml/coverage.xml"

[tool.pytest.ini_options]
addopts = [
  "-rxf",
  "-x",
  "-v",
  "-l",
  "--asyncio-mode=auto",
  "--junitxml=test_results/pytest.xml",
  "--cov=./custom_components",
  "--cov-report=xml",
  "--cov-report=html",
]
filterwarnings = ["ignore:ssl.PROTOCOL_TLS is deprecated:DeprecationWarning"]
testpaths = ["tests"]
python_files = ["test_*.py"]
