name: Pull actions

on:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - uses: "actions/checkout@v2"

        - name: HACS validation
          uses: "hacs/action@main"
          with:
            category: "integration"

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"

  style:
    runs-on: "ubuntu-latest"
    name: Check style formatting
    steps:
        - uses: "actions/checkout@v2"
        - uses: "actions/setup-python@v1"
          with:
            python-version: "3.x"
        - run: python3 -m pip install ruff
        - run: ruff check .

  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v2"
      - name: Setup Python
        uses: "actions/setup-python@v1"
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python3 -m pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@1.1.48
        with:
          pytest-xml-coverage-path: ./test_results/cov_xml/coverage.xml
          junitxml-path: ./test_results/pytest.xml
